package javscraper.io

import javscraper.models.Video
import java.nio.file.Files
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

class NfoReaderTest {
    @Test
    fun `read parses compatible fields and aliases`() {
        val nfo = Files.createTempFile("javscraper-nfo-", ".nfo")
        try {
            Files.writeString(
                nfo,
                """
                <movie>
                    <title>Test Title</title>
                    <originaltitle>Original Title</originaltitle>
                    <id>TEST-001</id>
                    <release>2023-1-2</release>
                    <runtime>119</runtime>
                    <rating>9.2</rating>
                    <director>Director</director>
                    <set><name>Series</name></set>
                    <studio>Maker</studio>
                    <label>Label</label>
                    <actor><name>Actor A</name></actor>
                    <actor><name>Actor B</name></actor>
                    <genre>Tag A</genre>
                    <tag>Tag A</tag>
                    <tag>Tag B</tag>
                    <plot>Summary</plot>
                    <thumb>cover.jpg</thumb>
                </movie>
                """.trimIndent()
            )

            val video = NfoReader.read(nfo)

            assertEquals(
                Video(
                    number = "TEST-001",
                    title = "Test Title",
                    actresses = listOf("Actor A", "Actor B"),
                    date = "2023-01-02",
                    maker = "Maker",
                    label = "Label",
                    series = "Series",
                    director = "Director",
                    duration = 119,
                    rating = 9.2,
                    tags = listOf("Tag A", "Tag B"),
                    posterUrl = "cover.jpg",
                    summary = "Summary"
                ),
                video
            )
        } finally {
            Files.deleteIfExists(nfo)
        }
    }

    @Test
    fun `read supports output generated by NfoWriter`() {
        val original = Video(
            number = "SONE-001",
            title = "Title",
            source = "fc2",
            detailUrl = "https://example.com/1723984",
            actresses = listOf("Actor"),
            date = "2024-02-03",
            maker = "Maker",
            label = "Label",
            series = "Series",
            director = "Director",
            duration = 120,
            rating = 8.8,
            tags = listOf("Tag"),
            summary = "Summary"
        )
        val nfo = Files.createTempFile("javscraper-nfo-", ".nfo")
        try {
            Files.writeString(nfo, NfoWriter.generate(original))

            val video = NfoReader.read(nfo)

            assertEquals(original, video)
        } finally {
            Files.deleteIfExists(nfo)
        }
    }

    @Test
    fun `read skips duplicate xml declaration generated by legacy writer`() {
        val nfo = Files.createTempFile("javscraper-legacy-", ".nfo")
        try {
            Files.writeString(
                nfo,
                "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                    "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"???>" +
                    "<movie><title>Legacy Title</title><originaltitle>LEGACY-001</originaltitle></movie>"
            )

            val video = NfoReader.read(nfo)

            assertEquals("LEGACY-001", video?.number)
            assertEquals("Legacy Title", video?.title)
        } finally {
            Files.deleteIfExists(nfo)
        }
    }
    @Test
    fun `read returns null for invalid xml and repairs bare ampersand`() {
        val invalid = Files.createTempFile("javscraper-invalid-", ".nfo")
        val ampersand = Files.createTempFile("javscraper-ampersand-", ".nfo")
        try {
            Files.writeString(invalid, "<movie><title>Broken</movie>")
            Files.writeString(ampersand, "<movie><title>AT&T</title><num>AMP-001</num></movie>")

            assertNull(NfoReader.read(invalid))
            assertEquals("AT&T", NfoReader.read(ampersand)?.title)
            assertTrue(NfoReader.read(ampersand)?.number == "AMP-001")
        } finally {
            Files.deleteIfExists(invalid)
            Files.deleteIfExists(ampersand)
        }
    }
}